---
title: "The Natural History and Fitness Landscape of Clonal Haematopoiesis"
subtitle: "Comparing different model formulations"
author: 
    - José Guilherme de Almeida
    - Moritz Gerstung
output: 
  html_document:
    theme: lumen
    highlight: tango
    code_folding: hide
    df_print: paged
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    number_sections: true
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,dpi = 300)
```

```{r import_functions, include=FALSE}
source("scripts/vaf_dynamics_functions.R")
model_file_name <- "models/model_F5_full.RDS"
dir.create("figures/model_comparison/",showWarnings = F)
set.seed(42)
source("scripts/prepare_data.R")
```

# Model A - single coefficient per gene and binomial sampling

$$
b_{gene_i} \sim N(0,0.1)
\\
u_{ji} \sim Uniform(-50,0)
\\
p_i = ilogit(b_{gene_i} * age + u_{ji})
\\
counts_i \sim Binom(coverage,p_i)
$$

```{r model_a_load_values}
model_file_name <- "models/model_A_full.RDS"
values_model <- readRDS(model_file_name)
model_id <- gsub('_$','',str_match(model_file_name,'model_.*_'))
dir.create("figures/",showWarnings = F)
dir.create(sprintf("figures/%s",model_id),showWarnings = F)
c(#'age_at_clone_foundation','dynamic_coefficients',
  #'inferred_trajectories','overdispersion',
  'statistical_analysis') %>%
  sapply(
    function(x) dir.create(sprintf("figures/%s/%s",model_id,x),showWarnings = F)
  )
```

``` {r model_a_dynamic_visualization_preparation, fig.width = 3.2,fig.height = 6}
val_subset <- values_model$training_subset

X_val <- val_subset$counts[values_model$gene_idxs,]
gene_idxs <- values_model$gene_idxs

interference_idxs <- values_model$interference_idxs %>% 
  mutate(ind_site = as.numeric(factor(paste(ind,site,sep = '-'))))
u_idx <- values_model$u_idx

b_gene_values_val <- values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'mean'] %>% 
  matrix(ncol=1) 
u_values_val <- values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'mean'] %>%
  matrix(nrow=1) 

ae_gene <- val_subset$gene_to_site_indicator[values_model$gene_idxs,] %*% b_gene_values_val
age_effect <- ae_gene[interference_idxs$site]
age_effect <- age_effect * (val_subset$ages[interference_idxs$ind_age] - values_model$min_age)
offset_per_individual <- u_values_val[interference_idxs$ind_site]
r <- age_effect + offset_per_individual
mu_val <- inv.logit(r) / 2

r_values <- data.frame(
  mu_val = mu_val,
  true = val_subset$counts[gene_idxs,][cbind(interference_idxs$site,interference_idxs$ind_age)],
  age = val_subset$ages[interference_idxs$ind_age],
  coverage = val_subset$coverage[gene_idxs,][cbind(interference_idxs$site,interference_idxs$ind_age)],
  individual = val_subset$unique_individual_true[interference_idxs$ind],
  coefficient_095 = values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'HDPI_high'][interference_idxs$site],
  coefficient = values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'mean'][interference_idxs$site],
  coefficient_005 = values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'HDPI_low'][interference_idxs$site],
  site = val_subset$unique_site[values_model$gene_idxs][interference_idxs$site],
  u_values_005 = c(values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'HDPI_low'][interference_idxs$ind_site]),
  u_values = c(values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'mean'][interference_idxs$ind_site]),
  u_values_095 = c(values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'HDPI_high'][interference_idxs$ind_site])
) %>%
  as.data.frame() %>%
  apply(1,FUN = function(x){
    mu_val <- as.numeric(x[1])
    cov <- as.numeric(x[4])
    Q <- rbinom(n = 1000,size = cov,prob = mu_val) %>%
      quantile(c(0.05,0.50,0.95))
    names(Q) <- c("pred_005","pred","pred_095")
    return(c(x,Q))
  }) %>% 
  t %>%
  as.data.frame() %>% 
  mutate(genes = sapply(as.character(site),function(x) unlist(strsplit(x,'-'))[[1]])) %>%
  group_by(site) %>%
  mutate(n = length(pred)) %>%
  ungroup() %>%
  mutate(
    mu_val = as.numeric(as.character(mu_val)),
    true = as.numeric(as.character(true)),
    age = as.numeric(as.character(age)),
    coverage = as.numeric(as.character(coverage)),
    individual = as.numeric(as.character(individual)),
    coefficient_005 = as.numeric(as.character(coefficient_005)),
    coefficient = as.numeric(as.character(coefficient)),
    coefficient_095 = as.numeric(as.character(coefficient_095)),
    pred_005 = as.numeric(as.character(pred_005)),
    pred = as.numeric(as.character(pred)),
    pred_095 = as.numeric(as.character(pred_095)),
    u_values_005 = as.numeric(as.character(u_values_005)),
    u_values = as.numeric(as.character(u_values)),
    u_values_095 = as.numeric(as.character(u_values_095))
  )

r_values_ <- r_values %>% 
  mutate(VAFpred = pred / coverage,
         VAFtrue = true / coverage) %>% 
  subset(coverage > 0) %>%
  group_by(individual,site) %>% 
  mutate(normalizedVAFpred = (VAFpred + 1) / (VAFpred[which(age == min(age))] + 1),
         normalizedVAFtrue = (VAFtrue + 1) / (VAFtrue[which(age == min(age))] + 1)) %>%
  ungroup() %>%
  mutate(individual = as.character(individual)) %>% 
  gather(key = 'key',value = 'value',VAFpred,VAFtrue) %>%
  mutate(
    pred_005 = ifelse(key == 'VAFpred',
                      pred_005 / coverage,
                      NA),
    pred_095 = ifelse(key == 'VAFpred',
                      pred_095 / coverage,
                      NA)
  ) 

r_values_list$model_a <- r_values
```

```{r model_a_summary_statistic, fig.height=4,fig.width=4}
order_same_rank <- function(v) {
  u <- unique(v)
  o <- rep(0,length(v))
  for (i in 1:length(u)) {
    o[v == u[i]] <- i
  }
  return(o)
}

beta_value <- values_model$beta_values[[1]][1,1]

statistic_full <- r_values_ %>%
  subset(key == 'VAFpred') %>%
  mutate(tail_prob = pbinom(
    q = true,
    size = coverage,
    prob = mu_val)) %>%
  group_by(site,individual) %>% 
  summarise(sum_stat = pchisq(sum(qnorm(tail_prob)^2),length(tail_prob)),
            gene = genes[1]) %>%
  mutate(split = 'full') %>%
  select(split,site,sum_stat,gene,individual) %>%
  ungroup() %>%
  mutate(recurring = site %in% values_model$training_subset$unique_site_multiple)

total_variants_explained <- statistic_full %>%
  group_by(site) %>%
  summarise(TotalExplainedVariants = sum(sum_stat < 0.7),
            TotalVariants = length(sum_stat))

statistic_aggregated <- r_values_ %>%
  subset(key == 'VAFpred') %>%
  mutate(
    tail_prob = pbinom(
    q = true,
    size = coverage,
    prob = mu_val)) %>%
  group_by(site) %>% 
  summarise(sum_stat = pchisq(sum(qnorm(tail_prob)^2),length(tail_prob)),
            gene = genes[1],
            MinimumAge = min(age),
            MaximumAge = max(age),
            MaxValue = max(c(pred_095,value,true/coverage),na.rm = T)) %>%
  mutate(split = 'full') %>%
  ungroup() %>%
  merge(total_variants_explained,by = c("site"))

p <- statistic_full %>%
  mutate(gene = str_match(gene,"[A-Z0-9]+")) %>% 
  group_by(gene) %>% 
  summarise(
    total = length(gene),
    good = sum(sum_stat < 0.7),
    bad = sum(sum_stat >= 0.7)
  ) %>% 
  gather("key","value",good,bad) %>%
  mutate(key = ifelse(key == 'good',"Good fit","Poor fit")) %>% 
  ggplot(aes(x = gene,y = value / total,fill = key)) +
  geom_bar(stat = "identity",color = "black") + 
  theme_minimal(base_size = 15) +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(face = 'italic')) + 
  xlab("") +
  ylab("Fraction of outliers") + 
  scale_y_continuous() + 
  scale_fill_lancet(name = NULL) + 
  rotate_x_text() 

p

statistic_full %>% 
  select(sum_stat) %>%
  mutate(sum_stat = sum_stat < .7) %>%
  table

statistics_lists$model_a <- list(
  individual_site = statistic_full,
  site = statistic_aggregated
)
```

```{r saving_everything_exporting_as_script}
r_values <- r_values_list$model_f2

save(r_values,statistics_data,clone_ages,file = sprintf('vaf_modelling_coefficients_%s.Rdata',model_id))

knitr::purl("vaf_modelling_paper_1.Rmd")
```


# Model B - gene and site coefficients and binomial sampling

$$
b_{gene_i} \sim N(0,0.1)
\\
b_{site_i} \sim N(0,0.1)
\\
u_{ji} \sim Uniform(-50,0)
\\
p_i = ilogit((b_{gene_i}+b_{site_i}) * age + u_{ji})
\\
counts_i \sim Binom(coverage,p_i)
$$

```{r model_b_load_values}
model_file_name <- "models/model_C_full.RDS"
values_model <- readRDS(model_file_name)
model_id <- gsub('_$','',str_match(model_file_name,'model_.*_'))
dir.create("figures/",showWarnings = F)
dir.create(sprintf("figures/%s",model_id),showWarnings = F)
c(#'age_at_clone_foundation','dynamic_coefficients',
  #'inferred_trajectories','overdispersion',
  'statistical_analysis') %>%
  sapply(
    function(x) dir.create(sprintf("figures/%s/%s",model_id,x),showWarnings = F)
  )
```

``` {r model_b_dynamic_visualization_preparation, fig.width = 3.2,fig.height = 6}
val_subset <- values_model$training_subset

X_val <- val_subset$counts[values_model$gene_idxs,]
gene_idxs <- values_model$gene_idxs

interference_idxs <- values_model$interference_idxs %>% 
  mutate(ind_site = as.numeric(factor(paste(ind,site,sep = '-'))))
u_idx <- values_model$u_idx

b_gene_values_val <- values_model$b_gene_values[[1]]$values[values_model$b_gene_values[[1]]$labels == 'mean'] %>% 
  matrix(ncol=1) 
b_site_values_val <- values_model$b_site_values[[1]]$values[values_model$b_site_values[[1]]$labels == 'mean'] %>% 
  matrix(ncol=1) 
u_values_val <- values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'mean'] %>%
  matrix(nrow=1) 

ae_gene <- val_subset$gene_to_site_indicator[values_model$gene_idxs,] %*% b_gene_values_val
ae_site <- val_subset$site_multiple_to_site_indicator[values_model$gene_idxs,] %*% b_site_values_val
age_effect <- ae_gene[interference_idxs$site] + ae_site[interference_idxs$site]
age_effect <- age_effect * (val_subset$ages[interference_idxs$ind_age] - values_model$min_age)
offset_per_individual <- u_values_val[interference_idxs$ind_site]
r <- age_effect + offset_per_individual
mu_val <- inv.logit(r) / 2

r_values <- data.frame(
  mu_val = mu_val,
  true = val_subset$counts[gene_idxs,][cbind(interference_idxs$site,interference_idxs$ind_age)],
  age = val_subset$ages[interference_idxs$ind_age],
  coverage = val_subset$coverage[gene_idxs,][cbind(interference_idxs$site,interference_idxs$ind_age)],
  individual = val_subset$unique_individual_true[interference_idxs$ind],
  coefficient_095 = values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'HDPI_high'][interference_idxs$site],
  coefficient = values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'mean'][interference_idxs$site],
  coefficient_005 = values_model$b_values[[1]]$values[values_model$b_values[[1]]$labels == 'HDPI_low'][interference_idxs$site],
  site = val_subset$unique_site[values_model$gene_idxs][interference_idxs$site],
  u_values_005 = c(values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'HDPI_low'][interference_idxs$ind_site]),
  u_values = c(values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'mean'][interference_idxs$ind_site]),
  u_values_095 = c(values_model$u_values[[1]]$values[values_model$u_values[[1]]$labels == 'HDPI_high'][interference_idxs$ind_site])
) %>%
  as.data.frame() %>%
  apply(1,FUN = function(x){
    mu_val <- as.numeric(x[1])
    cov <- as.numeric(x[4])
    Q <- rbinom(n = 1000,size = cov,prob = mu_val) %>%
      quantile(c(0.05,0.50,0.95))
    names(Q) <- c("pred_005","pred","pred_095")
    return(c(x,Q))
  }) %>% 
  t %>%
  as.data.frame() %>% 
  mutate(genes = sapply(as.character(site),function(x) unlist(strsplit(x,'-'))[[1]])) %>%
  group_by(site) %>%
  mutate(n = length(pred)) %>%
  ungroup() %>%
  mutate(
    mu_val = as.numeric(as.character(mu_val)),
    true = as.numeric(as.character(true)),
    age = as.numeric(as.character(age)),
    coverage = as.numeric(as.character(coverage)),
    individual = as.numeric(as.character(individual)),
    coefficient_005 = as.numeric(as.character(coefficient_005)),
    coefficient = as.numeric(as.character(coefficient)),
    coefficient_095 = as.numeric(as.character(coefficient_095)),
    pred_005 = as.numeric(as.character(pred_005)),
    pred = as.numeric(as.character(pred)),
    pred_095 = as.numeric(as.character(pred_095)),
    u_values_005 = as.numeric(as.character(u_values_005)),
    u_values = as.numeric(as.character(u_values)),
    u_values_095 = as.numeric(as.character(u_values_095))
  )

r_values_ <- r_values %>% 
  mutate(VAFpred = pred / coverage,
         VAFtrue = true / coverage) %>% 
  subset(coverage > 0) %>%
  group_by(individual,site) %>% 
  mutate(normalizedVAFpred = (VAFpred + 1) / (VAFpred[which(age == min(age))] + 1),
         normalizedVAFtrue = (VAFtrue + 1) / (VAFtrue[which(age == min(age))] + 1)) %>%
  ungroup() %>%
  mutate(individual = as.character(individual)) %>% 
  gather(key = 'key',value = 'value',VAFpred,VAFtrue) %>%
  mutate(
    pred_005 = ifelse(key == 'VAFpred',
                      pred_005 / coverage,
                      NA),
    pred_095 = ifelse(key == 'VAFpred',
                      pred_095 / coverage,
                      NA)
  ) 

r_values_list$model_c <- r_values
```

```{r model_a_summary_statistic, fig.height=4,fig.width=4}
order_same_rank <- function(v) {
  u <- unique(v)
  o <- rep(0,length(v))
  for (i in 1:length(u)) {
    o[v == u[i]] <- i
  }
  return(o)
}

statistic_full <- r_values_ %>%
  subset(key == 'VAFpred') %>%
  mutate(tail_prob = pbinom(
    q = true,
    size = coverage,
    prob = mu_val)) %>%
  group_by(site,individual) %>% 
  summarise(sum_stat = pchisq(sum(qnorm(tail_prob)^2),length(tail_prob)),
            gene = genes[1]) %>%
  mutate(split = 'full') %>%
  select(split,site,sum_stat,gene,individual) %>%
  ungroup() %>%
  mutate(recurring = site %in% values_model$training_subset$unique_site_multiple)

total_variants_explained <- statistic_full %>%
  group_by(site) %>%
  summarise(TotalExplainedVariants = sum(sum_stat < 0.7),
            TotalVariants = length(sum_stat))

statistic_aggregated <- r_values_ %>%
  subset(key == 'VAFpred') %>%
  mutate(
    tail_prob = pbinom(
    q = true,
    size = coverage,
    prob = mu_val)) %>%
  group_by(site) %>% 
  summarise(sum_stat = pchisq(sum(qnorm(tail_prob)^2),length(tail_prob)),
            gene = genes[1],
            MinimumAge = min(age),
            MaximumAge = max(age),
            MaxValue = max(c(pred_095,value,true/coverage),na.rm = T)) %>%
  mutate(split = 'full') %>%
  ungroup() %>%
  merge(total_variants_explained,by = c("site"))

p <- statistic_full %>%
  mutate(gene = str_match(gene,"[A-Z0-9]+")) %>% 
  group_by(gene) %>% 
  summarise(
    total = length(gene),
    good = sum(sum_stat < 0.7),
    bad = sum(sum_stat >= 0.7)
  ) %>% 
  gather("key","value",good,bad) %>%
  mutate(key = ifelse(key == 'good',"Good fit","Poor fit")) %>% 
  ggplot(aes(x = gene,y = value / total,fill = key)) +
  geom_bar(stat = "identity",color = "black") + 
  theme_minimal(base_size = 15) +
  theme(legend.position = 'bottom',
        axis.text.x = element_text(face = 'italic')) + 
  xlab("") +
  ylab("Fraction of outliers") + 
  scale_y_continuous() + 
  scale_fill_lancet(name = NULL) + 
  rotate_x_text() 

p

statistic_full %>% 
  select(sum_stat) %>%
  mutate(sum_stat = sum_stat < .7) %>%
  table

statistics_lists$model_a <- list(
  individual_site = statistic_full,
  site = statistic_aggregated
)
```

```{r saving_everything_exporting_as_script}
r_values <- r_values_list$model_f2

save(r_values,statistics_data,clone_ages,file = sprintf('vaf_modelling_coefficients_%s.Rdata',model_id))

knitr::purl("vaf_modelling_paper_1.Rmd")
```


# Session details

```{r session_details}
cat(system("git log -n1", intern=TRUE), sep="\n")
```

```{r session_objects}
l <- ls()
data.frame(variable=l, Reduce("rbind",lapply(l, function(x) data.frame(classes=paste(class(get(x)),collapse = ','), size=format(object.size(get(x)), units="auto")))))
```

```{r session_packages}
sessionInfo()
```